# Generated by Django 3.1.5 on 2021-01-05 12:27

from django.db import migrations, models

import haugebot_web.managers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TwitchUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('access_token', models.CharField(max_length=50)),
                ('refresh_token', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(null=True)),
            ],
            managers=[
                ('objects', haugebot_web.managers.TwitchUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WusstestDuSchon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertised_command', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=450)),
                ('use_prefix', models.BooleanField(default=True, verbose_name='Präfix verwenden')),
                ('active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_setting (key, value) VALUES('WusstestDuSchonPrefix', 'Psssst... wusstest du eigentlich schon,')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_setting (key, value) VALUES('WusstestDuSchonLoop', '10')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_setting (key, value) VALUES('WusstestDuSchonColor', 'HotPink')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (1, 'Red', 'Rot', '#ff0000')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (2, 'Blue', 'Blau', '#0000ff')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (3, 'Green', 'Grün', '#008000')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (4, 'FireBrick', 'Backstein', '#b22222')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (5, 'Coral', 'Korallenrot', '#ff7f50')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (6, 'YellowGreen', 'Gelbliches Grün', '#9acd32')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (7, 'OrangeRed', 'Orangenrot', '#ff4500')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (8, 'SeaGreen', 'Meeresgrün', '#2e8b57')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (9, 'GoldenRod', 'Goldrute', '#daa520')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (10, 'Chocolate', 'Schokoladenbraun', '#d2691e')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (11, 'CadetBlue', 'Marineblau', '#5f9ea0')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (12, 'DodgerBlue', 'Dodgerblau', '#1e90ff')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (13, 'HotPink', 'Leuchtendes Rosa', '#ff69b4')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (14, 'BlueViolet', 'Blauviolett', '#8a2be2')"
        ),
        migrations.RunSQL(
            "INSERT INTO haugebot_web_twitchcolor (id, twitch_name, display_name, color) VALUES (15, 'SpringGreen', 'Frühlingsgrün', '#00ff7f')"
        ),
    ]
