# Generated by Django 3.1.5 on 2021-01-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('haugebot_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchuser',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
