# Generated by Django 3.1.5 on 2021-01-13 22:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('haugebot_web', '0002_twitchuser_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipimeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiDelay', '15')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiThreshold1', '1')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiThreshold2', '3')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipimeterLoop', '10')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipimeterResetThreshold', '30')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiColor0', 'YellowGreen')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiColor1', 'Green')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiColor2', 'GoldenRod')"),
        migrations.RunSQL("INSERT INTO haugebot_web_setting(key, value) VALUES ('PipiColor3', 'Red')"),
    ]
