# Generated by Django 3.2.5 on 2021-07-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haugebot_web', '0003_pipimeter'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='label',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
