# Generated by Django 3.2.5 on 2021-07-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haugebot_web', '0004_setting_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='key',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='label',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='value',
        ),
        migrations.AddField(
            model_name='setting',
            name='wusstest_du_schon_loop',
            field=models.PositiveIntegerField(default=10, verbose_name='Pause (in Minuten)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='wusstest_du_schon_prefix',
            field=models.CharField(default='Psssst... wusstest du eigentlich schon,', max_length=50, verbose_name='Präfix'),
            preserve_default=False,
        ),
    ]
