# Generated by Django 3.2.10 on 2021-12-20 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haugebot_web', '0005_auto_20210727_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wusstestduschon',
            old_name='advertised_command',
            new_name='command',
        ),
        migrations.AlterField(
            model_name='pipimeter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='twitchcolor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wusstestduschon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
