# Generated by Django 3.2.10 on 2021-12-22 09:49

from django.db import migrations, models
import django


class Migration(migrations.Migration):

    dependencies = [
        ('haugebot_web', '0006_auto_20211220_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=500)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
