# Generated by Django 6.0 on 2025-12-14 17:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('haugebot_web', '0007_whisper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('interval', models.PositiveIntegerField(default=5)),
                ('next_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('announce', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haugebot_web.timer')),
            ],
        ),
        migrations.DeleteModel(
            name='Pipimeter',
        ),
        migrations.DeleteModel(
            name='TwitchColor',
        ),
    ]
